# Build Stage
FROM node:lts-alpine AS build
WORKDIR /app

# Install git
RUN apk add --no-cache git

# Clone repo
RUN git clone https://github.com/Chandra-Sekhar-02-45/BankingSystem.git .

# Install dependencies and build
WORKDIR /app/Client
RUN npm install
RUN npm run build

# Serve Stage
FROM nginx:alpine
COPY --from=build /app/Client/dist /usr/share/nginx/html
COPY deployments/K8s/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4040
CMD ["nginx", "-g", "daemon off;"]
