---
- name: Deploy Banking System to Minikube
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    frontend_image: rvcsraju/bankingfrontend:latest
    backend_image: rvcsraju/bankingbackend:latest
    repo_url: 'https://github.com/Chandra-Sekhar-02-45/BankingSystem.git'
    build_dir: "{{ playbook_dir }}/build_src"

  tasks:
    # Git clone is handled inside Dockerfiles now

    - name: Build Backend Docker Image inside Minikube
      shell: |
        eval $(minikube docker-env)
        docker build -t {{ backend_image }} -f "{{ playbook_dir }}/../k8s/Dockerfile.backend" .
      register: build_backend
      changed_when: "'Successfully built' in build_backend.stdout"

    - name: Build Frontend Docker Image inside Minikube
      shell: |
        eval $(minikube docker-env)
        docker build -t {{ frontend_image }} -f "{{ playbook_dir }}/../k8s/Dockerfile.frontend" .
      register: build_frontend
      changed_when: "'Successfully built' in build_frontend.stdout"

    - name: Apply Kubernetes Manifests
      command: kubectl apply -f "{{ playbook_dir }}/../k8s/deployment.yaml"
